### GET ALL PRODUCTS
GET http://localhost:4000/product

### GET PRODUCT BY ID
GET http://localhost:4000/product/ID_AQUI

### GET ALL CATEGORIES
GET http://localhost:4000/category

### GET CATEGORY BY ID
GET http://localhost:4000/category/ID_AQUI
